name: Bug Report
description: Report a Bug
title: "[Bug]: "
labels: ["bug"]
assignees: []


body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.


  - type: input
    id: environment
    attributes:
      label: Environment
      description: What environment are you running? (OS, python version, rstt version, etc)
      placeholder: "e.g.  macOS 13.5, python 3.12, rstt 0.6.7"
    validations:
      required: false

  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce your issue. Try to provide a deterministic code snippet.
      placeholder: |
        ```python
        pop = Player(...)
        ranking = Ranking(...)
        solver = BetterWin()
        data = ...
        ranking.update(data)
        ```
    validations:
      required: true


  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of the bug.
      placeholder: An updated ranking
    validations:
      required: true


  - type: textarea
    id: output
    attributes:
      label: Output
      description: What happened ?
      placeholder: |
        ```text
        KeyError: '...'
        ```
    validations:
      required: true


  - type: textarea
    id: information
    attributes:
      label: Additional Information
      description: Can you tell us more about it?
      placeholder: | 
        e.g. logs, related issues, links, ideas, debuggin notes
    validations:
      required: false

  - type: textarea
    id: fix
    attributes:
      label: Fix Suggestion
      description: Is there an easy fix you have in mind?
      placeholder: e.g code, or remarks
    validations:
      required: false

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribute
      description: How can you contribute?
      options:
        - label: I can implement the fix.
        - label: I could implement the fix, but have no experience with the codebase.
        - label: I have experience with the code base, but no idea how to fix it.
        - label: I can not implement a fix, but can investigate deeper the issue and report in comments below.
    validations:
      required: false 