name: pytest

on: [push, pull_request]

jobs:
  test:

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
    
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx ensurepath
          pipx install poetry
      - run: poetry install --no-interaction --no-root
      - run: poetry run pytest