name: pytest

on: [push, pull_request]

jobs:
  test:

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-22.04, macos-latest] # there seems to be issues with windows shell and the way snok install poetry
    
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
      - run: poetry install --no-interaction --no-root --with dev
      - run: poetry run pytest --cov --cov-branch --cov-report=xml
      - name: Coverage
        if: ${{ matrix.os == 'ubuntu-latest' &&  matrix.python-version == '3.10'}}
        uses: codecov/codecov-action@v3